from __future__ import annotations

import pathlib
import subprocess

ROOT = pathlib.Path(__file__).resolve().parents[1]


EXPECTED_PATHS = [
    "README.md",
    "LICENSE",
    "NOTICE",
    "CHANGELOG.md",
    "CODEOWNERS",
    "pyproject.toml",
    ".gitignore",
    "components/yamaha_serial/__init__.py",
    "components/yamaha_serial/yamaha_serial.h",
    "components/yamaha_serial/yamaha_serial.cpp",
    "components/yamaha_serial/sensor.py",
    "components/yamaha_serial/switch.py",
    "components/yamaha_serial/text_sensor.py",
    "components/yamaha_serial/binary_sensor.py",
    "components/yamaha_serial/number.py",
    "components/yamaha_serial/select.py",
    "components/yamaha_serial/button.py",
    "components/yamaha_serial/media_player.py",
    "custom_components/yamaha_serial_receiver/__init__.py",
    "custom_components/yamaha_serial_receiver/const.py",
    "custom_components/yamaha_serial_receiver/manifest.json",
    "custom_components/yamaha_serial_receiver/media_player.py",
    "examples/yamaha_rx_v_basic.yaml",
    "examples/yamaha_rx_v_full.yaml",
    "examples/yamaha_rx_vx500.yaml",
    "examples/home_assistant_companion.yaml",
    "examples/secrets.example.yaml",
    "docs/protocol.md",
    "docs/command_matrix.md",
    "docs/home_assistant_companion.md",
    "docs/profiles.md",
    "docs/supported_models.md",
    "docs/troubleshooting.md",
    "docs/wiring.md",
    "SECURITY.md",
    "SUPPORT.md",
    "PRIVACY.md",
    "hacs.json",
    "custom_components/yamaha_serial_receiver/brand/icon.png",
    "custom_components/yamaha_serial_receiver/brand/logo.png",
    "tools/check_compile_size.py",
    "tools/prepare_ci_configs.py",
    "tools/check_release_version.py",
    "tools/build_release_notes.py",
    ".github/dependabot.yml",
    ".github/codeql/codeql-config.yml",
    ".github/workflows/validate.yml",
    ".github/workflows/release.yml",
    ".github/workflows/codeql.yml",
    ".github/ISSUE_TEMPLATE/config.yml",
    ".github/ISSUE_TEMPLATE/bug_report.yml",
    ".github/ISSUE_TEMPLATE/feature_request.yml",
    ".github/ISSUE_TEMPLATE/support_question.yml",
]


def test_expected_files_exist() -> None:
    missing = [path for path in EXPECTED_PATHS if not (ROOT / path).exists()]
    assert not missing, f"Missing expected files: {missing}"


def test_no_obvious_todo_placeholders() -> None:
    scan_paths = [
        ROOT / "components/yamaha_serial",
        ROOT / "custom_components/yamaha_serial_receiver",
        ROOT / "docs",
        ROOT / "examples",
        ROOT / "README.md",
    ]
    offenders: list[str] = []
    for path in scan_paths:
        if path.is_file():
            lines = path.read_text(encoding="utf-8").splitlines()
            for idx, line in enumerate(lines, start=1):
                if "TODO" in line or "TBD" in line:
                    offenders.append(f"{path}:{idx}:{line.strip()}")
            continue
        for file in path.rglob("*"):
            if not file.is_file():
                continue
            try:
                lines = file.read_text(encoding="utf-8").splitlines()
            except UnicodeDecodeError:
                continue
            for idx, line in enumerate(lines, start=1):
                if "TODO" in line or "TBD" in line:
                    offenders.append(f"{file}:{idx}:{line.strip()}")
    assert not offenders, "Found placeholder markers:\n" + "\n".join(offenders)


# The brand assets are generated by this project and contain no vendor mark.
# HACS requires them, so they are the one allowed exception to the image ban
# that keeps vendor manual scans out of the repository.
ALLOWED_BINARY_PATHS = {
    "custom_components/yamaha_serial_receiver/brand/icon.png",
    "custom_components/yamaha_serial_receiver/brand/icon@2x.png",
    "custom_components/yamaha_serial_receiver/brand/logo.png",
    "custom_components/yamaha_serial_receiver/brand/logo@2x.png",
}


def test_no_vendor_manual_or_generated_artifacts_are_tracked() -> None:
    forbidden_suffixes = {
        ".pdf",
        ".doc",
        ".docx",
        ".zip",
        ".7z",
        ".rar",
        ".jpg",
        ".jpeg",
        ".png",
        ".gif",
        ".webp",
    }
    tracked_files = subprocess.check_output(
        ["git", "ls-files"],
        cwd=ROOT,
        text=True,
    ).splitlines()
    offenders: list[str] = []
    for rel_path in tracked_files:
        path = pathlib.Path(rel_path)
        if rel_path in ALLOWED_BINARY_PATHS:
            continue
        if path.suffix.lower() in forbidden_suffixes:
            offenders.append(rel_path)
        if any(part in {"__pycache__", "build", "dist"} for part in path.parts):
            offenders.append(rel_path)
        if any(part.endswith(".egg-info") for part in path.parts):
            offenders.append(rel_path)
    assert not offenders, "Tracked or repository-local artifacts need review:\n" + "\n".join(offenders)
